# Site Settings
title: Nalini Singh
email: nalini_singh@berkeley.edu
baseurl: ""
email_address: nalini_singh@berkeley.edu
linkedin_username: nalinimsingh
twitter_username: nalinimsingh
github_username: nalinimsingh
# Build Settings
sass:
  sass_dir: _sass
markdown: kramdown
kramdown:
  input: GFM
