# Site Settings
title: Nalini Singh
email: nmsingh@mit.edu
baseurl: ""
email_address: nmsingh@mit.edu
linkedin_username: nalinimsingh
twitter_username: nalinimsingh
github_username: nalinimsingh
# Build Settings
sass:
  sass_dir: _sass
markdown: kramdown
kramdown:
  input: GFM
